- name: Run show commands on routers
  hosts: cisco_routers
  gather_facts: false

  tasks:
  - name: sh ip inter br
    raw: sh ip inter br
    register: sh_ip_int_br_result

  - name: debug registered var
    debug: var=sh_ip_int_br_result.stdout_lines
